const PDFDocument = require('pdfkit')

function streamBrandedPdf(res, { school, title, filename, lines }) {
  const doc = new PDFDocument({ margin: 50, size: 'A4' })
  const primary = school?.secondaryColor || '#0b1f4a'
  const accent = school?.primaryColor || '#f59e0b'
  const schoolName = school?.name || 'SchoolPilot'

  res.setHeader('Content-Type', 'application/pdf')
  res.setHeader('Content-Disposition', `attachment; filename="${filename}.pdf"`)
  doc.pipe(res)

  doc.rect(0, 0, doc.page.width, 80).fill(primary)
  doc.fillColor('#ffffff').fontSize(18).text(schoolName, 50, 28, { align: 'center', width: doc.page.width - 100 })
  doc.fontSize(12).text(title, 50, 52, { align: 'center', width: doc.page.width - 100 })

  doc.fillColor('#111827').moveDown(3)
  for (const line of lines) {
    if (typeof line === 'string') {
      doc.fontSize(11).font('Helvetica').text(line)
    } else if (line?.divider) {
      doc.moveDown(0.5).moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor(accent).stroke().moveDown(0.5)
    } else {
      doc.fontSize(line.size || 11).font(line.bold ? 'Helvetica-Bold' : 'Helvetica').text(line.text, line.opts || {})
      doc.font('Helvetica')
    }
  }

  doc.fillColor('#64748b').fontSize(9).text(
    `Generated by ${schoolName}`,
    50,
    doc.page.height - 60,
    { align: 'center', width: doc.page.width - 100 }
  )

  doc.end()
}

module.exports = { streamBrandedPdf }
