/** SchoolPilot subscription plan limits & feature matrix */

const DEFAULT_LIMITS = {
  maxStudents: null,
  maxTeachers: null,
  maxStaff: null,
  maxParents: null,
  storageGb: 5,
  aiCredits: 0,
  smsCredits: 0,
  monthlyEmails: 500,
  campuses: 1,
  website: false,
  studentPortal: false,
  parentPortal: false,
  teacherPortal: false,
  attendance: false,
  results: false,
  assignments: false,
  timetable: false,
  fees: false,
  manualPayments: false,
  emailNotifications: false,
  basicReports: false,
  dashboard: false,
  cbt: false,
  admission: false,
  lms: false,
  videoLessons: false,
  messaging: false,
  library: false,
  hostel: false,
  transport: false,
  news: false,
  blog: false,
  gallery: false,
  advancedReports: false,
  ai: false,
  liveClasses: false,
  qrCertificates: false,
  digitalIdCards: false,
  alumni: false,
  marketplace: false,
  admissionCrm: false,
  parentAiReports: false,
  hr: false,
  payroll: false,
  performanceReviews: false,
  leaveManagement: false,
  revenueAnalytics: false,
  teacherAnalytics: false,
  studentForecasting: false,
  gpsTracking: false,
  biometric: false,
  apiAccess: false,
  dedicatedAccountManager: false,
  prioritySupport: false,
  whiteLabel: false,
  customDomain: false,
  unlimitedStorage: false,
  premiumAi: false,
  customIntegrations: false,
  disasterRecovery: false,
  highAvailability: false,
  customSla: false,
  customDevelopment: false,
}

const PLAN_PRESETS = {
  starter: {
    maxStudents: 300,
    maxTeachers: 30,
    maxStaff: 15,
    storageGb: 5,
    aiCredits: 0,
    smsCredits: 50,
    monthlyEmails: 500,
    campuses: 1,
    website: true,
    studentPortal: true,
    parentPortal: true,
    teacherPortal: true,
    attendance: true,
    results: true,
    assignments: true,
    timetable: true,
    fees: true,
    manualPayments: true,
    emailNotifications: true,
    basicReports: true,
    dashboard: true,
    marketplace: false,
    hr: false,
    payroll: false,
    hostel: false,
    transport: false,
    biometric: false,
    liveClasses: false,
    lms: false,
    cbt: false,
    admission: false,
    ai: false,
    alumni: false,
    customDomain: false,
    prioritySupport: false,
  },
  standard: {
    maxStudents: 800,
    maxTeachers: 80,
    maxStaff: 40,
    storageGb: 20,
    aiCredits: 0,
    smsCredits: 200,
    monthlyEmails: 2000,
    campuses: 1,
    website: true,
    studentPortal: true,
    parentPortal: true,
    teacherPortal: true,
    attendance: true,
    results: true,
    assignments: true,
    timetable: true,
    fees: true,
    manualPayments: true,
    emailNotifications: true,
    basicReports: true,
    dashboard: true,
    cbt: true,
    admission: true,
    lms: true,
    videoLessons: true,
    messaging: true,
    library: true,
    hostel: true,
    transport: true,
    news: true,
    blog: true,
    gallery: true,
    advancedReports: true,
    marketplace: false,
    hr: false,
    payroll: false,
    biometric: false,
    liveClasses: false,
    ai: false,
    alumni: false,
    customDomain: false,
    prioritySupport: false,
  },
  professional: {
    maxStudents: 2000,
    maxTeachers: 200,
    maxStaff: 100,
    storageGb: 50,
    aiCredits: 500,
    smsCredits: 500,
    monthlyEmails: 10000,
    campuses: 3,
    website: true,
    studentPortal: true,
    parentPortal: true,
    teacherPortal: true,
    attendance: true,
    results: true,
    assignments: true,
    timetable: true,
    fees: true,
    manualPayments: true,
    emailNotifications: true,
    basicReports: true,
    dashboard: true,
    cbt: true,
    admission: true,
    lms: true,
    videoLessons: true,
    messaging: true,
    library: true,
    hostel: true,
    transport: true,
    news: true,
    blog: true,
    gallery: true,
    advancedReports: true,
    ai: true,
    liveClasses: true,
    qrCertificates: true,
    digitalIdCards: true,
    alumni: true,
    marketplace: true,
    admissionCrm: true,
    parentAiReports: true,
    hr: false,
    payroll: false,
    biometric: false,
    gpsTracking: false,
    customDomain: true,
    prioritySupport: false,
  },
  enterprise: {
    maxStudents: 5000,
    maxTeachers: 500,
    maxStaff: 250,
    storageGb: 200,
    aiCredits: 2000,
    smsCredits: 2000,
    monthlyEmails: 50000,
    campuses: 10,
    website: true,
    studentPortal: true,
    parentPortal: true,
    teacherPortal: true,
    attendance: true,
    results: true,
    assignments: true,
    timetable: true,
    fees: true,
    manualPayments: true,
    emailNotifications: true,
    basicReports: true,
    dashboard: true,
    cbt: true,
    admission: true,
    lms: true,
    videoLessons: true,
    messaging: true,
    library: true,
    hostel: true,
    transport: true,
    news: true,
    blog: true,
    gallery: true,
    advancedReports: true,
    ai: true,
    liveClasses: true,
    qrCertificates: true,
    digitalIdCards: true,
    alumni: true,
    marketplace: true,
    admissionCrm: true,
    parentAiReports: true,
    hr: true,
    payroll: true,
    performanceReviews: true,
    leaveManagement: true,
    revenueAnalytics: true,
    teacherAnalytics: true,
    studentForecasting: true,
    gpsTracking: true,
    biometric: true,
    apiAccess: true,
    dedicatedAccountManager: true,
    prioritySupport: true,
    whiteLabel: true,
    customDomain: true,
  },
  ultimate: {
    maxStudents: null,
    maxTeachers: null,
    maxStaff: null,
    storageGb: null,
    aiCredits: 10000,
    smsCredits: 10000,
    monthlyEmails: null,
    campuses: null,
    unlimitedStorage: true,
    premiumAi: true,
    customIntegrations: true,
    disasterRecovery: true,
    highAvailability: true,
    customSla: true,
    customDevelopment: true,
    website: true,
    studentPortal: true,
    parentPortal: true,
    teacherPortal: true,
    attendance: true,
    results: true,
    assignments: true,
    timetable: true,
    fees: true,
    manualPayments: true,
    emailNotifications: true,
    basicReports: true,
    dashboard: true,
    cbt: true,
    admission: true,
    lms: true,
    videoLessons: true,
    messaging: true,
    library: true,
    hostel: true,
    transport: true,
    news: true,
    blog: true,
    gallery: true,
    advancedReports: true,
    ai: true,
    liveClasses: true,
    qrCertificates: true,
    digitalIdCards: true,
    alumni: true,
    marketplace: true,
    admissionCrm: true,
    parentAiReports: true,
    hr: true,
    payroll: true,
    performanceReviews: true,
    leaveManagement: true,
    revenueAnalytics: true,
    teacherAnalytics: true,
    studentForecasting: true,
    gpsTracking: true,
    biometric: true,
    apiAccess: true,
    dedicatedAccountManager: true,
    prioritySupport: true,
    whiteLabel: true,
    customDomain: true,
  },
}

const PLAN_FEATURE_LABELS = {
  website: 'School Website',
  studentPortal: 'Student Portal',
  parentPortal: 'Parent Portal',
  teacherPortal: 'Teacher Portal',
  attendance: 'Attendance',
  results: 'Results',
  assignments: 'Assignments',
  timetable: 'Timetable',
  fees: 'Fee Management',
  manualPayments: 'Manual Payment Verification',
  emailNotifications: 'Email Notifications',
  basicReports: 'Basic Reports',
  dashboard: 'Responsive Dashboard',
  cbt: 'CBT Examination',
  admission: 'Admission Portal',
  lms: 'LMS',
  videoLessons: 'Video Lessons',
  messaging: 'Internal Messaging',
  library: 'Library Module',
  hostel: 'Hostel Module',
  transport: 'Transport Module',
  news: 'News',
  blog: 'Blog',
  gallery: 'Gallery',
  advancedReports: 'Advanced Reports',
  ai: 'AI Suite',
  liveClasses: 'Live Classes',
  qrCertificates: 'QR Certificates',
  digitalIdCards: 'Digital ID Cards',
  alumni: 'Alumni System',
  marketplace: 'Marketplace',
  admissionCrm: 'Admission CRM',
  parentAiReports: 'Parent AI Reports',
  hr: 'HR Management',
  payroll: 'Payroll',
  performanceReviews: 'Staff Performance Reviews',
  leaveManagement: 'Leave Management',
  revenueAnalytics: 'Revenue Analytics',
  teacherAnalytics: 'Teacher Analytics',
  studentForecasting: 'Student Forecasting',
  gpsTracking: 'GPS Bus Tracking',
  biometric: 'Fingerprint & Face Recognition',
  apiAccess: 'API Access',
  dedicatedAccountManager: 'Dedicated Account Manager',
  prioritySupport: 'Priority Support',
  unlimitedStorage: 'Unlimited Storage',
  premiumAi: 'Premium AI',
  customIntegrations: 'Custom Integrations',
  disasterRecovery: 'Disaster Recovery',
  highAvailability: 'High Availability',
  customSla: 'Custom SLA',
  customDevelopment: 'Custom Development',
}

const MODULE_KEY_MAP = {
  marketplace: 'marketplace',
  payroll: 'payroll',
  hostel: 'hostel',
  transport: 'transport',
  alumni: 'alumni',
  biometric: 'biometric',
  liveClasses: 'liveClasses',
  lms: 'lms',
  admission: 'admission',
  hr: 'hr',
  ai: 'ai',
  cbt: 'cbt',
  library: 'library',
}

const PLAN_ORDER = ['starter', 'standard', 'professional', 'enterprise', 'ultimate']

const LEGACY_SLUG_MAP = { basic: 'starter', premium: 'professional' }

function resolvePlanSlug(slug) {
  return LEGACY_SLUG_MAP[slug] || slug
}

function mergeLimits(plan) {
  const slug = resolvePlanSlug(plan?.slug || '')
  const preset = PLAN_PRESETS[slug] || {}
  const fromDb = typeof plan?.limits === 'object' && plan.limits !== null ? plan.limits : {}
  return { ...DEFAULT_LIMITS, ...preset, ...fromDb }
}

function planFeaturesFromLimits(limits) {
  return {
    lms: !!limits.lms,
    ai: !!limits.ai || (limits.aiCredits || 0) > 0,
    cbt: !!limits.cbt,
    marketplace: !!limits.marketplace,
    payroll: !!limits.payroll,
    hr: !!limits.hr,
    biometric: !!limits.biometric,
    liveClasses: !!limits.liveClasses,
    transport: !!limits.transport,
    hostel: !!limits.hostel,
    library: !!limits.library,
    admission: !!limits.admission,
  }
}

function priceForInterval(plan, interval) {
  if (plan?.contactSales) return null
  if (interval === 'yearly' && plan.yearlyPrice) return plan.yearlyPrice
  if (interval === 'quarterly' && plan.quarterlyPrice) return plan.quarterlyPrice
  return plan.price
}

function isFeatureEnabled(limits, featureKey) {
  const merged = limits?.maxStudents != null ? limits : mergeLimits({ slug: '', limits })
  if (merged[featureKey] === true) return true
  if (merged[featureKey] === false) return false
  return !!merged[featureKey]
}

function minimumPlanForFeature(featureKey) {
  for (const slug of PLAN_ORDER) {
    if (PLAN_PRESETS[slug]?.[featureKey]) return slug
  }
  return 'ultimate'
}

function comparePlans(currentSlug, requiredSlug) {
  const a = PLAN_ORDER.indexOf(resolvePlanSlug(currentSlug))
  const b = PLAN_ORDER.indexOf(resolvePlanSlug(requiredSlug))
  if (a < 0 || b < 0) return false
  return a >= b
}

function listPlanFeatures(slug) {
  const limits = mergeLimits({ slug })
  return Object.entries(PLAN_FEATURE_LABELS)
    .filter(([key]) => limits[key])
    .map(([key, label]) => ({ key, label, enabled: true }))
}

function buildComparisonMatrix() {
  return PLAN_ORDER.map((slug) => ({
    slug,
    name: slug.charAt(0).toUpperCase() + slug.slice(1),
    features: listPlanFeatures(slug),
    limits: mergeLimits({ slug }),
  }))
}

module.exports = {
  DEFAULT_LIMITS,
  PLAN_PRESETS,
  PLAN_FEATURE_LABELS,
  PLAN_ORDER,
  MODULE_KEY_MAP,
  LEGACY_SLUG_MAP,
  resolvePlanSlug,
  mergeLimits,
  planFeaturesFromLimits,
  priceForInterval,
  isFeatureEnabled,
  minimumPlanForFeature,
  comparePlans,
  listPlanFeatures,
  buildComparisonMatrix,
}
