import type { Plan } from '../components/billing/PricingCards'

/** Shown when /api/subscription-plans is unreachable (e.g. Vercel without backend). */
export const FALLBACK_PLANS: Plan[] = [
  {
    id: 'fallback-starter',
    name: 'Starter',
    slug: 'starter',
    price: 25000,
    quarterlyPrice: 70000,
    yearlyPrice: 270000,
    maxStudents: 300,
    isPopular: false,
    contactSales: false,
    planFeatures: [
      { key: 'studentPortal', label: 'Student Portal' },
      { key: 'parentPortal', label: 'Parent Portal' },
      { key: 'teacherPortal', label: 'Teacher Portal' },
      { key: 'attendance', label: 'Attendance' },
      { key: 'results', label: 'Results' },
      { key: 'fees', label: 'Fee Management' },
      { key: 'website', label: 'School Website' },
      { key: 'dashboard', label: 'Responsive Dashboard' },
    ],
  },
  {
    id: 'fallback-standard',
    name: 'Standard',
    slug: 'standard',
    price: 50000,
    quarterlyPrice: 140000,
    yearlyPrice: 540000,
    maxStudents: 800,
    isPopular: false,
    contactSales: false,
    planFeatures: [
      { key: 'cbt', label: 'CBT Examination' },
      { key: 'admission', label: 'Admission Portal' },
      { key: 'lms', label: 'LMS' },
      { key: 'library', label: 'Library Module' },
      { key: 'messaging', label: 'Internal Messaging' },
      { key: 'news', label: 'News' },
      { key: 'blog', label: 'Blog' },
      { key: 'gallery', label: 'Gallery' },
    ],
  },
  {
    id: 'fallback-professional',
    name: 'Professional',
    slug: 'professional',
    price: 90000,
    quarterlyPrice: 255000,
    yearlyPrice: 972000,
    maxStudents: 2000,
    isPopular: true,
    contactSales: false,
    planFeatures: [
      { key: 'ai', label: 'AI Suite' },
      { key: 'liveClasses', label: 'Live Classes' },
      { key: 'hostel', label: 'Hostel Module' },
      { key: 'transport', label: 'Transport Module' },
      { key: 'marketplace', label: 'Marketplace' },
      { key: 'alumni', label: 'Alumni System' },
      { key: 'advancedReports', label: 'Advanced Reports' },
      { key: 'digitalIdCards', label: 'Digital ID Cards' },
    ],
  },
  {
    id: 'fallback-enterprise',
    name: 'Enterprise',
    slug: 'enterprise',
    price: 180000,
    quarterlyPrice: 510000,
    yearlyPrice: 1944000,
    maxStudents: 5000,
    isPopular: false,
    contactSales: false,
    planFeatures: [
      { key: 'hr', label: 'HR Management' },
      { key: 'payroll', label: 'Payroll' },
      { key: 'biometric', label: 'Biometric Attendance' },
      { key: 'revenueAnalytics', label: 'Revenue Analytics' },
      { key: 'teacherAnalytics', label: 'Teacher Analytics' },
      { key: 'parentAiReports', label: 'Parent AI Reports' },
      { key: 'prioritySupport', label: 'Priority Support' },
      { key: 'customDomain', label: 'Custom Domain' },
    ],
  },
  {
    id: 'fallback-ultimate',
    name: 'Ultimate',
    slug: 'ultimate',
    price: 0,
    quarterlyPrice: null,
    yearlyPrice: null,
    maxStudents: null,
    isPopular: false,
    contactSales: true,
    planFeatures: [
      { key: 'whiteLabel', label: 'White Label' },
      { key: 'customSla', label: 'Custom SLA' },
      { key: 'dedicatedAccountManager', label: 'Dedicated Account Manager' },
      { key: 'customIntegrations', label: 'Custom Integrations' },
      { key: 'highAvailability', label: 'High Availability' },
      { key: 'customDevelopment', label: 'Custom Development' },
    ],
  },
]
