export type NavItem = {
  href: string
  label: string
  roles: string[]
  section?: string
}

export const NAV_ITEMS: NavItem[] = [
  { href: '/dashboard', label: 'Overview', roles: ['SuperAdmin', 'SchoolAdmin', 'Teacher', 'Student', 'Parent', 'Accountant'], section: 'Main' },
  { href: '/super-admin', label: 'Platform Dashboard', roles: ['SuperAdmin'], section: 'Super Admin' },
  { href: '/super-admin/schools', label: 'Schools', roles: ['SuperAdmin'], section: 'Super Admin' },
  { href: '/super-admin/plans', label: 'Subscription Plans', roles: ['SuperAdmin'], section: 'Super Admin' },
  { href: '/super-admin/billing', label: 'Billing', roles: ['SuperAdmin'], section: 'Super Admin' },
  { href: '/super-admin/referrals', label: 'Referrals', roles: ['SuperAdmin'], section: 'Super Admin' },
  { href: '/super-admin/feature-flags', label: 'Feature Flags', roles: ['SuperAdmin'], section: 'Super Admin' },
  { href: '/super-admin/support', label: 'Support Desk', roles: ['SuperAdmin'], section: 'Super Admin' },
  { href: '/super-admin/communications', label: 'Communications', roles: ['SuperAdmin'], section: 'Super Admin' },
  { href: '/admin/setup-wizard', label: 'Setup wizard', roles: ['SchoolAdmin'], section: 'School' },
  { href: '/admin/school-branding', label: 'Branding', roles: ['SchoolAdmin'], section: 'School' },
  { href: '/admin/website-cms', label: 'Website CMS', roles: ['SuperAdmin', 'SchoolAdmin'], section: 'School' },
  { href: '/admin/billing', label: 'Billing', roles: ['SchoolAdmin'], section: 'School' },
  { href: '/super-admin/system-health', label: 'System Health', roles: ['SuperAdmin'], section: 'Super Admin' },
  { href: '/admin/referrals', label: 'Referral Program', roles: ['SchoolAdmin'], section: 'School' },
  { href: '/admin/support', label: 'Support', roles: ['SchoolAdmin'], section: 'School' },
  { href: '/super-admin/users', label: 'All Users', roles: ['SuperAdmin'], section: 'Super Admin' },
  { href: '/admin/students', label: 'Students', roles: ['SuperAdmin', 'SchoolAdmin'], section: 'School' },
  { href: '/admin/teachers', label: 'Teachers', roles: ['SuperAdmin', 'SchoolAdmin'], section: 'School' },
  { href: '/admin/classes', label: 'Classes', roles: ['SuperAdmin', 'SchoolAdmin'], section: 'School' },
  { href: '/admin/subjects', label: 'Subjects', roles: ['SuperAdmin', 'SchoolAdmin'], section: 'School' },
  { href: '/admin/sessions', label: 'Sessions', roles: ['SuperAdmin', 'SchoolAdmin'], section: 'School' },
  { href: '/admin/terms', label: 'Terms', roles: ['SuperAdmin', 'SchoolAdmin'], section: 'School' },
  { href: '/admin/results', label: 'Results', roles: ['SuperAdmin', 'SchoolAdmin'], section: 'School' },
  { href: '/admin/admissions', label: 'Admissions CRM', roles: ['SuperAdmin', 'SchoolAdmin'], section: 'School' },
  { href: '/hr', label: 'HR Dashboard', roles: ['SuperAdmin', 'SchoolAdmin', 'HRManager'], section: 'HR' },
  { href: '/hr/jobs', label: 'Job Postings', roles: ['SuperAdmin', 'SchoolAdmin', 'HRManager'], section: 'HR' },
  { href: '/hr/applications', label: 'Applications', roles: ['SuperAdmin', 'SchoolAdmin', 'HRManager'], section: 'HR' },
  { href: '/hr/employees', label: 'Employees', roles: ['SuperAdmin', 'SchoolAdmin', 'HRManager'], section: 'HR' },
  { href: '/hr/leave', label: 'Leave Requests', roles: ['SuperAdmin', 'SchoolAdmin', 'HRManager'], section: 'HR' },
  { href: '/payroll', label: 'Payroll Dashboard', roles: ['SuperAdmin', 'SchoolAdmin', 'HRManager', 'Accountant'], section: 'Payroll' },
  { href: '/admin/broadsheets', label: 'Broadsheets', roles: ['SuperAdmin', 'SchoolAdmin', 'Teacher'], section: 'Reports' },
  { href: '/admin/library', label: 'Library Books', roles: ['SuperAdmin', 'SchoolAdmin'], section: 'School' },
  { href: '/admin/library-transactions', label: 'Library Transactions', roles: ['SuperAdmin', 'SchoolAdmin'], section: 'School' },
  { href: '/admin/hostel', label: 'Hostel Rooms', roles: ['SuperAdmin', 'SchoolAdmin'], section: 'School' },
  { href: '/admin/hostel-allocations', label: 'Hostel Allocations', roles: ['SuperAdmin', 'SchoolAdmin'], section: 'School' },
  { href: '/admin/transport', label: 'Transport Dashboard', roles: ['SuperAdmin', 'SchoolAdmin'], section: 'School' },
  { href: '/admin/transport-routes', label: 'Transport Routes', roles: ['SuperAdmin', 'SchoolAdmin'], section: 'School' },
  { href: '/admin/transport-vehicles', label: 'Transport Vehicles', roles: ['SuperAdmin', 'SchoolAdmin'], section: 'School' },
  { href: '/admin/transport-allocations', label: 'Transport Allocations', roles: ['SuperAdmin', 'SchoolAdmin'], section: 'School' },
  { href: '/admin/biometrics', label: 'Biometrics', roles: ['SuperAdmin', 'SchoolAdmin'], section: 'School' },
  { href: '/admin/biometric-devices', label: 'Biometric Devices', roles: ['SuperAdmin', 'SchoolAdmin'], section: 'School' },
  { href: '/admin/biometric-enrollments', label: 'Biometric Enrollments', roles: ['SuperAdmin', 'SchoolAdmin'], section: 'School' },
  { href: '/admin/biometric-access-logs', label: 'Access Logs', roles: ['SuperAdmin', 'SchoolAdmin'], section: 'School' },
  { href: '/admin/certificates', label: 'Certificates', roles: ['SuperAdmin', 'SchoolAdmin'], section: 'School' },
  { href: '/admin/id-cards', label: 'ID Cards', roles: ['SuperAdmin', 'SchoolAdmin'], section: 'School' },
  { href: '/admin/alumni', label: 'Alumni', roles: ['SuperAdmin', 'SchoolAdmin'], section: 'School' },
  { href: '/admin/alumni-donations', label: 'Donation confirmations', roles: ['SuperAdmin', 'SchoolAdmin'], section: 'School' },
  { href: '/admin/marketplace', label: 'Marketplace', roles: ['SuperAdmin', 'SchoolAdmin'], section: 'School' },
  { href: '/admin/marketplace-orders', label: 'Shop Orders', roles: ['SuperAdmin', 'SchoolAdmin'], section: 'School' },
  { href: '/admin/lms-courses', label: 'LMS Courses', roles: ['SuperAdmin', 'SchoolAdmin', 'Teacher'], section: 'School' },
  { href: '/admin/live-classes', label: 'Live Classes', roles: ['SuperAdmin', 'SchoolAdmin', 'Teacher'], section: 'School' },
  { href: '/admin/cbt-exams', label: 'CBT Exams', roles: ['SuperAdmin', 'SchoolAdmin', 'Teacher'], section: 'School' },
  { href: '/admin/cbt-question-banks', label: 'Question Banks', roles: ['SuperAdmin', 'SchoolAdmin', 'Teacher'], section: 'School' },
  { href: '/admin/analytics', label: 'Analytics Hub', roles: ['SuperAdmin', 'SchoolAdmin'], section: 'Reports' },
  { href: '/admin/analytics/principal', label: 'Principal Dashboard', roles: ['SuperAdmin', 'SchoolAdmin'], section: 'Reports' },
  { href: '/admin/analytics/proprietor', label: 'Proprietor Dashboard', roles: ['SuperAdmin', 'SchoolAdmin'], section: 'Reports' },
  { href: '/admin/audit-logs', label: 'Audit logs', roles: ['SuperAdmin', 'SchoolAdmin'], section: 'Reports' },
  { href: '/admin/usage', label: 'Usage & AI credits', roles: ['SchoolAdmin'], section: 'School' },
  { href: '/admin/email-settings', label: 'Email system', roles: ['SchoolAdmin'], section: 'School' },
  { href: '/admin/notification-settings', label: 'SMS & push', roles: ['SuperAdmin', 'SchoolAdmin'], section: 'School' },
  { href: '/settings/security', label: 'Security', roles: ['SuperAdmin', 'SchoolAdmin', 'Teacher', 'Student', 'Parent', 'Accountant', 'Librarian', 'HostelManager', 'TransportManager', 'BiometricManager', 'HRManager', 'Alumni'], section: 'Account' },
  { href: '/settings/notifications', label: 'Notifications', roles: ['SuperAdmin', 'SchoolAdmin', 'Teacher', 'Student', 'Parent', 'Accountant', 'Alumni'], section: 'Account' },
  { href: '/teacher/id-card', label: 'My ID Card', roles: ['Teacher', 'HRManager', 'Accountant', 'Librarian', 'HostelManager', 'TransportManager', 'BiometricManager'], section: 'Account' },
  { href: '/admin/reports-students', label: 'Student Performance', roles: ['SuperAdmin', 'SchoolAdmin'], section: 'Reports' },
  { href: '/teacher', label: 'My Portal', roles: ['Teacher'], section: 'Teacher' },
  { href: '/teacher/analytics', label: 'My Analytics', roles: ['Teacher'], section: 'Teacher' },
  { href: '/teacher/grading', label: 'Grade Entry', roles: ['Teacher'], section: 'Teacher' },
  { href: '/teacher/timetable', label: 'Timetable', roles: ['Teacher'], section: 'Teacher' },
  { href: '/teacher/mark-attendance', label: 'Mark Attendance', roles: ['Teacher'], section: 'Teacher' },
  { href: '/teacher/submissions', label: 'Grade Submissions', roles: ['Teacher'], section: 'Teacher' },
  { href: '/teacher/assignments', label: 'Assignments', roles: ['Teacher'], section: 'Teacher' },
  { href: '/teacher/lesson-plans', label: 'AI Lesson Plans', roles: ['Teacher', 'SchoolAdmin'], section: 'Teacher' },
  { href: '/teacher/ai-exams', label: 'AI Exam Generator', roles: ['Teacher', 'SchoolAdmin'], section: 'Teacher' },
  { href: '/teacher/ai-marking', label: 'AI Marking', roles: ['Teacher', 'SchoolAdmin'], section: 'Teacher' },
  { href: '/teacher/messages', label: 'Messages', roles: ['Teacher'], section: 'Teacher' },
  { href: '/teacher/leave', label: 'Leave', roles: ['Teacher'], section: 'Teacher' },
  { href: '/teacher/payslips', label: 'Payslips', roles: ['Teacher'], section: 'Teacher' },
  { href: '/teacher/notifications', label: 'Notifications', roles: ['Teacher'], section: 'Teacher' },
  { href: '/student', label: 'My Portal', roles: ['Student'], section: 'Student' },
  { href: '/student/results', label: 'My Results', roles: ['Student'], section: 'Student' },
  { href: '/student/fees', label: 'My Fees', roles: ['Student'], section: 'Student' },
  { href: '/student/timetable', label: 'Timetable', roles: ['Student'], section: 'Student' },
  { href: '/student/attendance', label: 'Attendance', roles: ['Student'], section: 'Student' },
  { href: '/student/messages', label: 'Messages', roles: ['Student'], section: 'Student' },
  { href: '/student/notifications', label: 'Notifications', roles: ['Student'], section: 'Student' },
  { href: '/student/library', label: 'Library', roles: ['Student'], section: 'Student' },
  { href: '/student/hostel', label: 'Hostel', roles: ['Student'], section: 'Student' },
  { href: '/student/transport', label: 'Transport', roles: ['Student'], section: 'Student' },
  { href: '/student/certificates', label: 'Certificates', roles: ['Student'], section: 'Student' },
  { href: '/student/id-card', label: 'ID Card', roles: ['Student'], section: 'Student' },
  { href: '/student/shop', label: 'School Shop', roles: ['Student'], section: 'Student' },
  { href: '/student/cbt', label: 'Online Tests', roles: ['Student'], section: 'Student' },
  { href: '/student/courses', label: 'Online Courses', roles: ['Student'], section: 'Student' },
  { href: '/student/live-classes', label: 'Live Classes', roles: ['Student'], section: 'Student' },
  { href: '/student/ai-tutor', label: 'AI Assistant', roles: ['Student'], section: 'Student' },
  { href: '/parent', label: 'Parent Portal', roles: ['Parent'], section: 'Parent' },
  { href: '/parent/children', label: 'My Children', roles: ['Parent'], section: 'Parent' },
  { href: '/parent/results', label: 'Results', roles: ['Parent'], section: 'Parent' },
  { href: '/parent/fees', label: 'Fees', roles: ['Parent'], section: 'Parent' },
  { href: '/parent/attendance', label: 'Attendance', roles: ['Parent'], section: 'Parent' },
  { href: '/parent/transport', label: 'Bus Tracking', roles: ['Parent'], section: 'Parent' },
  { href: '/parent/shop', label: 'School Shop', roles: ['Parent'], section: 'Parent' },
  { href: '/parent/ai-summary', label: 'AI Summary', roles: ['Parent'], section: 'Parent' },
  { href: '/parent/notifications', label: 'Notifications', roles: ['Parent'], section: 'Parent' },
  { href: '/accountant/finance', label: 'Financial Dashboard', roles: ['Accountant', 'SuperAdmin', 'SchoolAdmin'], section: 'Finance' },
  { href: '/accountant/payments', label: 'Verify Payments', roles: ['Accountant', 'SuperAdmin', 'SchoolAdmin'], section: 'Finance' },
  { href: '/admin/fee-adjustments', label: 'Fee adjustments', roles: ['Accountant', 'SuperAdmin', 'SchoolAdmin'], section: 'Finance' },
  { href: '/payroll/runs', label: 'Payroll Runs', roles: ['SuperAdmin', 'SchoolAdmin', 'HRManager', 'Accountant'], section: 'Payroll' },
  { href: '/payroll/profiles', label: 'Salary Profiles', roles: ['SuperAdmin', 'SchoolAdmin', 'HRManager', 'Accountant'], section: 'Payroll' },
  { href: '/payroll/grades', label: 'Salary Grades', roles: ['SuperAdmin', 'SchoolAdmin', 'HRManager', 'Accountant'], section: 'Payroll' },
  { href: '/admin/library', label: 'Library', roles: ['Librarian'], section: 'Librarian' },
  { href: '/admin/library-transactions', label: 'Issue & Return', roles: ['Librarian'], section: 'Librarian' },
  { href: '/admin/hostel', label: 'Hostel Rooms', roles: ['HostelManager'], section: 'Hostel' },
  { href: '/admin/hostel-allocations', label: 'Allocations', roles: ['HostelManager'], section: 'Hostel' },
  { href: '/admin/transport', label: 'Dashboard', roles: ['TransportManager'], section: 'Transport' },
  { href: '/admin/transport-routes', label: 'Routes', roles: ['TransportManager'], section: 'Transport' },
  { href: '/admin/transport-vehicles', label: 'Vehicles', roles: ['TransportManager'], section: 'Transport' },
  { href: '/admin/transport-allocations', label: 'Allocations', roles: ['TransportManager'], section: 'Transport' },
  { href: '/admin/biometrics', label: 'Dashboard', roles: ['BiometricManager'], section: 'Biometrics' },
  { href: '/admin/biometric-devices', label: 'Devices', roles: ['BiometricManager'], section: 'Biometrics' },
  { href: '/admin/biometric-enrollments', label: 'Enrollments', roles: ['BiometricManager'], section: 'Biometrics' },
  { href: '/admin/biometric-access-logs', label: 'Access Logs', roles: ['BiometricManager'], section: 'Biometrics' },
  { href: '/alumni', label: 'Alumni Portal', roles: ['Alumni'], section: 'Alumni' },
  { href: '/alumni/directory', label: 'Directory', roles: ['Alumni'], section: 'Alumni' },
  { href: '/alumni/events', label: 'Events', roles: ['Alumni'], section: 'Alumni' },
  { href: '/alumni/donate', label: 'Donate', roles: ['Alumni'], section: 'Alumni' },
  { href: '/alumni/mentorship', label: 'Mentorship', roles: ['Alumni'], section: 'Alumni' },
]

export function navForRole(role: string): NavItem[] {
  const items = NAV_ITEMS.filter((item) => item.roles.includes(role))
  if (role === 'SuperAdmin') {
    const allowed = new Set(['Main', 'Super Admin', 'Account'])
    return items.filter((item) => allowed.has(item.section || 'Main'))
  }
  return items
}

export const ROLE_HOME: Record<string, string> = {
  SuperAdmin: '/super-admin',
  SchoolAdmin: '/dashboard',
  Teacher: '/teacher',
  Student: '/student',
  Parent: '/parent',
  Accountant: '/accountant/finance',
  Librarian: '/admin/library',
  HostelManager: '/admin/hostel',
  TransportManager: '/admin/transport',
  BiometricManager: '/admin/biometrics',
  HRManager: '/hr',
  Alumni: '/alumni',
}

export const ROLE_LABELS: Record<string, string> = {
  SuperAdmin: 'Super Admin',
  SchoolAdmin: 'School Admin',
  Teacher: 'Teacher',
  Student: 'Student',
  Parent: 'Parent',
  Accountant: 'Accountant',
  Librarian: 'Librarian',
  HostelManager: 'Hostel Manager',
  TransportManager: 'Transport Manager',
  BiometricManager: 'Biometric Manager',
  HRManager: 'HR Manager',
  Alumni: 'Alumni',
}
